default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV["TEST_DB_USERNAME"] %>
  password: '<%= ENV["TEST_DB_PASSWORD"] %>'
  host: <%= ENV["TEST_DB_HOST"] %>
  port: 3306

development:
  <<: *default
  database: spec_ops
